name: Project Request
description: Submit a new project with team members
title: "[Project]: "
labels: ["project-request"]
body:
  - type: markdown
    attributes:
      value: |
        ## New Project Request
        Fill out the form below to create a new repository.

        **Enter your project name in the title above** (after `[Project]: `)

  - type: dropdown
    id: template
    attributes:
      label: Template Repository
      description: Select the template to use for your project
      options:
        - nestjs-template
        - react-template
        - nextjs-template
      default: 0
    validations:
      required: true

  - type: textarea
    id: github-accounts
    attributes:
      label: GitHub Accounts
      description: List the GitHub usernames of team members (one per line) - they will be added as collaborators
      placeholder: |
        octocat
        hubot
        monalisa
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Project Description
      description: Brief description of the project (optional)
      placeholder: "Describe what this project is about..."
    validations:
      required: false

  - type: checkboxes
    id: private-repo
    attributes:
      label: Repository Visibility
      options:
        - label: Make this repository private
          required: false
